In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os
import glob

import random
import math
import time
import datetime
import warnings

warnings.filterwarnings("ignore")

In [4]:
AIS_20_01_01_filepath = (
    r"D:\\Maritime_Vessel_monitoring\\csv_extracted_data\AIS_2020_01_01",
)
AIS_20_01_02_filepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_02",
)
AIS_20_01_03_filepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_03",
)
AIS_20_01_04_filepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_04",
)
AIS_20_01_05_filepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_05",
)
AIS_20_01_06_fiilepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_06",
)
AIS_20_01_07_fiilepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_07",
)
AIS_20_01_08_fiilepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_08",
)
AIS_20_01_09_fiilepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_09",
)
AIS_20_01_10_fiilepath = (
    r"D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_10"
)

In [5]:
AIS_2020_01_03 = pd.read_csv(
    "D:\Maritime_Vessel_monitoring\csv_extracted_data\AIS_2020_01_03\AIS_2020_01_03.csv"
)

AIS_2020_01_03.head(10)

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
0,368020640,2020-01-03T00:00:00,40.63936,-80.47423,0.0,360.0,511.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
1,367683579,2020-01-03T00:00:00,40.12194,-91.51325,0.0,112.2,511.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A
2,368053210,2020-01-03T00:00:01,57.77782,-152.41355,0.0,307.9,224.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A
3,316036089,2020-01-03T00:00:00,45.36721,-87.08709,13.3,236.0,235.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
4,368051230,2020-01-03T00:00:00,40.73179,-73.97286,0.1,65.7,352.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
5,367784560,2020-01-03T00:00:00,42.31011,-70.92978,27.2,143.5,145.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
6,368014850,2020-01-03T00:00:00,36.99912,-89.16047,0.0,276.9,311.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A
7,368021610,2020-01-03T00:00:02,61.12165,-146.34386,0.4,56.9,267.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
8,368053730,2020-01-03T00:00:01,37.84575,-122.40823,34.4,158.2,159.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
9,368119110,2020-01-03T00:00:00,30.13727,-85.62593,0.0,7.2,1.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A

In [6]:
AIS_2020_01_03["BaseDateTime"] = pd.to_datetime(
    AIS_2020_01_03["BaseDateTime"],
    format="%Y-%m-%dT%H:%M:%S",  # our data’s format: YYYY-MM-DDTHH:MM:SS
    errors="coerce",
)

AIS_2020_01_03.head(10)

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TransceiverClass
0,368020640,2020-01-03 00:00:00,40.63936,-80.47423,0.0,360.0,511.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
1,367683579,2020-01-03 00:00:00,40.12194,-91.51325,0.0,112.2,511.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A
2,368053210,2020-01-03 00:00:01,57.77782,-152.41355,0.0,307.9,224.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A
3,316036089,2020-01-03 00:00:00,45.36721,-87.08709,13.3,236.0,235.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
4,368051230,2020-01-03 00:00:00,40.73179,-73.97286,0.1,65.7,352.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
5,367784560,2020-01-03 00:00:00,42.31011,-70.92978,27.2,143.5,145.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
6,368014850,2020-01-03 00:00:00,36.99912,-89.16047,0.0,276.9,311.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A
7,368021610,2020-01-03 00:00:02,61.12165,-146.34386,0.4,56.9,267.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
8,368053730,2020-01-03 00:00:01,37.84575,-122.40823,34.4,158.2,159.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,A
9,368119110,2020-01-03 00:00:00,30.13727,-85.62593,0.0,7.2,1.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,A

In [7]:
AIS_2020_01_03.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7118203 entries, 0 to 7118202
Data columns (total 17 columns):
 #   Column            Dtype
---  ------            -----
 0   MMSI              int64
 1   BaseDateTime      datetime64[ns]
 2   LAT               float64
 3   LON               float64
 4   SOG               float64
 5   COG               float64
 6   Heading           float64
 7   VesselName        object
 8   IMO               object
 9   CallSign          object
 10  VesselType        float64
 11  Status            float64
 12  Length            float64
 13  Width             float64
 14  Draft             float64
 15  Cargo             float64
 16  TransceiverClass  object
dtypes: datetime64[ns](1), float64(11), int64(1), object(4)
memory usage: 923.2+ MB

# Predictive Analytics & Anomaly Detection


•	Develop and validate vessel trajectory prediction models using statistical and machine learning methods (Kalman Filters, ARIMA, LSTM, etc.).

•	Implement trajectory consistency checks to verify whether a vessel’s latest reported position aligns with its historical movement pattern.

•	Create anomaly detection algorithms for identifying sudden deviations, spoofing, or inconsistent data patterns.